M48
; DRILL file {KiCad (6.0.0)} date Wed Jul  6 21:22:19 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-06T21:22:19+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X195.525Y-139.7
X200.025Y-135.2
X200.025Y-144.2
X204.525Y-139.7
T2
X200.0Y-139.7
T0
M30
